# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths {
  /home/thomas/daala_zynq/daala_idct4_stream_1.0
  /home/thomas/daala_zynq/daala_idct4_mmap_1.0
} [current_fileset]
read_verilog /home/thomas/daala_zynq/daala_idct4_stream_1.0/hdl/daala_idct4_stream_v1_0.v
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/thomas/daala_zynq/daala_idct4_stream_1.0/edit_ip.data/wt [current_project]
set_property parent.project_dir /home/thomas/daala_zynq/daala_idct4_stream_1.0 [current_project]
synth_design -top daala_idct4_stream_v1_0 -part xc7z020clg484-1
write_checkpoint daala_idct4_stream_v1_0.dcp
report_utilization -file daala_idct4_stream_v1_0_utilization_synth.rpt -pb daala_idct4_stream_v1_0_utilization_synth.pb
